# Generated by Django 5.0.7 on 2024-08-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('post_url', models.CharField(help_text='Đường dẫn bài viết', max_length=1000, null=True)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(help_text='Tên mục tiêu', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('content', models.TextField(blank=True, help_text='Nội dung', null=True)),
                ('total_likes', models.IntegerField(default=0, help_text='Lượt thích')),
                ('total_comments', models.IntegerField(default=0, help_text='Lượt bình luận')),
                ('total_shares', models.IntegerField(default=0, help_text='Lượt chia sẻ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('target_name', models.CharField(help_text='Tên mục tiêu', max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostPartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_partofspeech', models.CharField(help_text='Tên mục tiêu', max_length=150)),
                ('description_partofspeech', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('content_partofspeech', models.TextField(blank=True, help_text='Nội dung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostWordSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_segmentation', models.CharField(help_text='Tên mục tiêu', max_length=150)),
                ('description_segmentation', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('content_segmentation', models.TextField(blank=True, help_text='Nội dung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.post')),
            ],
        ),
        migrations.CreateModel(
            name='TargetChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('target_url', models.CharField(help_text='Đường dẫn mục tiêu', max_length=1000, null=True)),
                ('category', models.CharField(help_text='Danh mục của mục tiêu', max_length=100, null=True)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.target')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='targetchild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.targetchild'),
        ),
    ]
